version: '3.4'

services:
  dockerautopublish:
    image: ${DOCKER_REGISTRY-}dockerautopublish
    build:
      context: .
      dockerfile: DockerAutoPublish/Dockerfile


  webapplication3:
    image: ${DOCKER_REGISTRY-}webapplication3
    build:
      context: .
      dockerfile: WebApplication3/Dockerfile

